version: '3'

services:
  app:
    container_name: 'zat-api'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - 'appdata:/var/lib/app/data'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zat
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    restart: always

  db:
    container_name: 'db'
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zat
      - TZ=America/Sao_Paulo
    volumes:
      - 'dbdata:/var/lib/mysql'
volumes:
  dbdata:
  appdata:
