FROM node:alpine

WORKDIR /usr/app

COPY package.json ./
COPY yarn.lock ./
COPY .env ./
COPY prisma ./prisma/

RUN yarn

RUN yarn prisma generate

COPY . .

EXPOSE 4000

CMD sleep 10 && yarn start:dev